---
# Create users and add them to specific groups
# ansible all -i localhost, -m debug -a "msg={{ 'jasonJiBJmuDvR3orYjQ' | password_hash('sha512', '') }}"
# ansible all -i localhost, -m debug -a "msg={{ 'bobsf8UkFCJah6mJf7Kw' | password_hash('sha512', '') }}"
# ansible all -i localhost, -m debug -a "msg={{ 'mikeHz3bGfs9XTWdBnMp' | password_hash('sha512', '') }}"
# ansible all -i localhost, -m debug -a "msg={{ 'ryanrMLLEs7rb29hiVgN' | password_hash('sha512', '') }}"
# ansible all -i localhost, -m debug -a "msg={{ 'brainPX8vjVhb98a3pEb' | password_hash('sha512', '') }}"

- name: Create groups and users
  hosts: rockies
  become: true

  tasks:
    - name: "Create Velo groups - Not required for real Velo"
      ansible.builtin.group:
        name: "{{ item }}"
        state: present
      loop: "{{ velo_groups }}"

    - name: Create NetArch users
      ansible.builtin.user:
        append: true
        comment: "{{ item.comment }}"
        groups: "{{ user_groups }}"
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        password_expire_max: 90
        password_expire_min: 7
        state: present
        update_password: on_create
      loop: "{{ velo_users }}"

    - name: Expire user passwords
      shell: "chage --lastday 0 {{ item.name }}"
      loop: "{{ velo_users }}"

    - name: Create .ssh directory for jason user
      ansible.builtin.file:
        path: /home/jason/.ssh
        owner: jason
        group: jason
        mode: "0700"
        state: directory

    - name: Add ssh keys to jason user
      ansible.builtin.copy:
        content: |
          test_key1 foo@bar
          test_key2 bar@bat
          test_key3 bat@baz
        dest: /home/jason/.ssh/authorized_keys
        mode: "0644"
        owner: jason