---
# Create users and add them to specific groups
# ansible all -i localhost, -m debug -a "msg={{ 'jasonJiBJmuDvR3orYjQ' | password_hash('sha512', '') }}"
# ansible all -i localhost, -m debug -a "msg={{ 'bobsf8UkFCJah6mJf7Kw' | password_hash('sha512', '') }}"
# ansible all -i localhost, -m debug -a "msg={{ 'mikeHz3bGfs9XTWdBnMp' | password_hash('sha512', '') }}"
# ansible all -i localhost, -m debug -a "msg={{ 'ryanrMLLEs7rb29hiVgN' | password_hash('sha512', '') }}"
# ansible all -i localhost, -m debug -a "msg={{ 'brainPX8vjVhb98a3pEb' | password_hash('sha512', '') }}"

- name: Create groups and users
  hosts: rockies
  become: true

  vars:
    ansible_user: josue
    ansible_password: kanyewestisnotthebest
    velo_groups:
      - vcadmin
      - adm
      - cdrom
      - netdev
      - sudo
    velo_users:
      - name: jason
        password: "$6$2Jrmh8Ip6VKWY8Un$Z21UpJOLwZp1pAIeFYIG86TAiJKhLUXbc0ZSL8uLqMNyAqq56JlspD9T1ze2zyWO1W2lZAeI4P9a2N36Kyy6n/"
        comment: Jason S
      - name: robert
        password: "$6$crRFuKomSMt4j8Ee$IiH3EEZL9lP1Cffym3unJ3JGsfUrwQQUunb7qNcQeTLeL90hm2.2ed6GPZ25J1fO0hCl.GLwWFSdT8CQwRv1o1"
        comment: Robert K
      - name: michael
        password: "$6$oFHMeOKipj4Bsap3$QXuX.Il6B5Yp3LGg5Vu2NEQx2LKJ9RHJZWrYj/V8SdP1/WaJqxhDGv.6ns.q28naVwYuJTRutuBCPgHvntJEq0"
        comment: Michael W
      - name: ryan
        password: "$6$tbsCsaKVsiGhGKiL$k26jjeO0HzEsk1O9f87nE9q52iS1c4BL2I7QNPfb6cyTWlMgn8Tc42iFrtkuQWQk6jWgpSPXaOc6AtG50uEQu/"
        comment: Ryan K
      - name: netbrain
        password: "$6$9BKJaGeMNIBGujLM$5TVMu..KIinyg.C0AIdsx2M7qdbUXeAZsqp5l9AbLC4e60hH8qO0Qc3tWZ5OtiQVaSRgSVjXL3cHsEc3SJgjK/"
        comment: NetBrain
    user_groups: vcadmin,adm,cdrom,sudo,netdev

  tasks:
    - name: "Create Velo groups - Not required for real Velo"
      ansible.builtin.group:
        name: "{{ item }}"
        state: present
      loop: "{{ velo_groups }}"

    - name: Create NetArch users
      ansible.builtin.user:
        append: true
        comment: "{{ item.comment }}"
        groups: "{{ user_groups }}"
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        password_expire_max: 90
        password_expire_min: 7
        state: present
        update_password: on_create
      loop: "{{ velo_users }}"

    - name: Expire user passwords
      shell: "chage --lastday 0 {{ item.name }}"
      loop: "{{ velo_users }}"

    - name: Create .ssh directory for jason user
      ansible.builtin.file:
        path: /home/jason/.ssh
        owner: jason
        group: jason
        mode: "0700"
        state: directory

    - name: Add ssh keys to jason user
      ansible.builtin.copy:
        content: |
          test_key1 foo@bar
          test_key2 bar@bat
          test_key3 bat@baz
        dest: /home/jason/.ssh/authorized_keys
        mode: "0644"
        owner: jason