---
- name: Update user password
  hosts: rocky3
  become: true
  vars_prompt:
    - name: username
      prompt: Enter your username
      private: false
    - name: new_pw
      prompt: Enter your new password. It must be at least 20 characters long.
      confirm: yes
      private: true
  vars:
    tower_user_name: netbrain

  tasks:
    - name: Verify user exists
      ansible.builtin.shell: "grep {{ username }} /etc/passwd"
      register: user_exists
      failed_when: false

    - name: Update password if user running this playbook matches the username provided
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ new_pw | password_hash('sha512', '') }}"
        state: present
        update_password: always
      when: username == tower_user_name and user_exists.rc == 0 and new_pw|length > 19
