---
- name: Update user password
  hosts: rocky3
  become: true
  vars_prompt:
    - name: username
      prompt: Enter your username
      private: false
    - name: current_pw_hash
      prompt: Enter your current password hash without quotes
      private: false
    - name: new_pw
      prompt: Enter your new password
      confirm: yes
      private: true
  vars:
    last_day: "{{ 90 if username not in ['netbrain', 'tower'] else 365 }}"
    username_length: "{{ username | length }}"

  tasks:

    - name: Check if current password hash in is /etc/shadow
      ansible.builtin.shell: "sudo grep '{{ current_pw_hash }}' /etc/shadow"
      register: shadow_hash


    - name: Update password if current password hash matches username
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ new_pw | password_hash('sha512', '') }}"
        state: present
        update_password: always
      when: username == shadow_hash.stdout[:username_length|int]
      register: pw_updt_result
